<?php

namespace OZiTAG\Tager\Backend\Auth;

use OZiTAG\Tager\Backend\Auth\Helpers\ProvidersHelper;
use OZiTAG\Tager\Backend\Auth\Scopes\TokenProviderScope;
use Illuminate\Foundation\Support\Providers\EventServiceProvider;
use Illuminate\Support\Facades\Route;
use Laravel\Passport\Token;
use OZiTAG\Tager\Backend\Auth\Observers\TokenObserver;
use OZiTAG\Tager\Backend\Auth\Middlewares\Provider;
use OZiTAG\Tager\Backend\Auth\Middlewares\Passport;

class AuthServiceProvider extends EventServiceProvider
{

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub

        $this->registerRoutes();
    }

    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        parent::boot();

        Token::observe(TokenObserver::class);
        Token::addGlobalScope(new TokenProviderScope);

        app('router')->aliasMiddleware('passport', Passport::class);

        $this->loadMigrationsFrom(__DIR__ . '/../migrations');
    }

    protected function registerRoutes() {
        Route::pattern('provider', implode('|', ProvidersHelper::getProviderAliases()));
        $this->loadRoutesFrom(__DIR__ . '/../routes/routes.php');
    }
}
