<?php

namespace OZiTAG\Tager\Backend\Auth;

use Illuminate\Support\Facades\Config;
use Laravel\Passport\Http\Middleware\CheckClientCredentials;
use OZiTAG\Tager\Backend\Auth\Helpers\ProvidersHelper;
use OZiTAG\Tager\Backend\Auth\Scopes\TokenProviderScope;
use Illuminate\Foundation\Support\Providers\EventServiceProvider;
use Illuminate\Support\Facades\Route;
use Laravel\Passport\Token;
use OZiTAG\Tager\Backend\Auth\Observers\TokenObserver;
use OZiTAG\Tager\Backend\Auth\Middlewares\Provider;
use OZiTAG\Tager\Backend\Auth\Middlewares\Passport;
use OZiTAG\Tager\Backend\Rbac\RbacServiceProvider;

class AuthServiceProvider extends EventServiceProvider
{

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub

        $this->mergeConfigFrom(__DIR__ . '/../config/config.php', 'tager-auth');

        if (Config::get('tager-auth.hash_clients_secrets')) {
            \Laravel\Passport\Passport::hashClientSecrets();
        }

        $this->registerRoutes();
        $this->app->register(RbacServiceProvider::class);
    }

    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        parent::boot();

        Token::observe(TokenObserver::class);
        Token::addGlobalScope(new TokenProviderScope);

        app('router')->aliasMiddleware('passport', Passport::class);
        app('router')->aliasMiddleware('client', CheckClientCredentials::class);

        $this->loadMigrationsFrom(__DIR__ . '/../migrations');
    }

    protected function registerRoutes() {
        Route::pattern('provider', implode('|', ProvidersHelper::getProviderAliases()));
        $this->loadRoutesFrom(__DIR__ . '/../routes/routes.php');
    }
}
